### ISSUE TITLE
A problem about Ref

### ISSUE THREAD

**Issue by cpWhitecat** [tanqingyao/tmusic#1]
https://github.com/tanqingyao/tmusic/blob/65336a5e15716c3c20a0635c1a7a948efa345b35/src/views/player/comps/Audio.vue#L35

Hi , guys,Ref is a type? I'm not a TypeScript user, Is it  TypeScript Syntax? Searching it , can't found solution the problem.

**Comment by cpWhitecat** [comment]
Ref is a interface??

**Comment by cpWhitecat** [comment]
Ref just a interface , i discover a problem again , https://github.com/tanqingyao/tmusic/blob/65336a5e15716c3c20a0635c1a7a948efa345b35/src/views/player/comps/Audio.vue#L35
https://github.com/tanqingyao/tmusic/blob/65336a5e15716c3c20a0635c1a7a948efa345b35/src/views/player/comps/Audio.vue#L4 , in line 4 , it works after Mounted , maybe it's value will been replaced ? or trigger ref() ?

**Comment by tanqingyao** [comment]
Yes, in vue, Ref  is type of ref, write this in order to typescript checker pass. This project use an early version of Vue3 and latest version is no need write the ref type.
Usually we get the dom instance by the ref api, your guess of ref work is probability right.

**Comment by cpWhitecat** [comment]
Thanks a lot , now ,I also can use API to do some simple operation , I find this repo in juejin ,and I remember that you create article about this repo in 2021 . hhhhh
